using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using VisionGrabber.Utilities;

namespace VisionGrabber.Backends
{
    /// <summary>
    /// Implements a backend that communicates with Google's Gemini API.
    /// </summary>
    public class GeminiBackend : IBackend
    {
        public GeminiBackend()
        {
        }

        /// <summary>
        /// Updates the API key.
        /// </summary>
        /// <param name="newKey">The new API key.</param>
        public void UpdateKey(string newKey)
        {
            // Pull from settings directly if needed for compatibility
            if (SettingsManager.Current != null)
            {
               SettingsManager.Current.CloudApiKey = newKey;
            }
        }

        /// <summary>
        /// Sends an image processing request to the Gemini API.
        /// </summary>
        /// <param name="base64Image">The image encoded as a base64 string.</param>
        /// <param name="userPrompt">The prompt to send with the image.</param>
        /// <returns>The text generated by the model.</returns>
        public async Task<string> SendImageRequest(string base64Image, string userPrompt)
        {
            var settings = SettingsManager.Current;
            string apiKey = settings.CloudApiKey;
            string modelId = settings.CloudModelId;

            if (string.IsNullOrWhiteSpace(apiKey))
                return "Error: Gemini API Key is missing. Please check Settings.";
            
            if (string.IsNullOrWhiteSpace(modelId))
                modelId = "gemini-2.0-flash-lite"; // Fallback default

            using (var client = new HttpClient())
            {
                var url = $"https://generativelanguage.googleapis.com/v1beta/models/{modelId}:generateContent?key={apiKey}";

                var payload = new
                {
                    contents = new[]
                    {
                        new
                        {
                            parts = new object[]
                            {
                                new { text = userPrompt },
                                new 
                                { 
                                    inline_data = new 
                                    { 
                                        mime_type = "image/png", 
                                        data = base64Image 
                                    } 
                                }
                            }
                        }
                    }
                };

                var json = JsonConvert.SerializeObject(payload);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                try
                {
                    var response = await client.PostAsync(url, content);
                    var responseString = await response.Content.ReadAsStringAsync();

                    if (!response.IsSuccessStatusCode)
                    {
                        return $"Gemini Error ({response.StatusCode}): {responseString}";
                    }

                    dynamic result = JsonConvert.DeserializeObject(responseString);
                    
                    // Parse the Gemini response
                    string text = result?.candidates?[0]?.content?.parts?[0]?.text;
                    return text ?? "No text returned from Gemini.";
                }
                catch (Exception ex)
                {
                    return "Error connecting to Gemini: " + ex.Message;
                }
            }
        }
    }
}
