using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using VisionGrabber.Utilities;

namespace VisionGrabber.Backends
{
    /// <summary>
    /// Implements a backend that communicates with another VisionGrabber instance acting as a relay server.
    /// </summary>
    public class RelayBackend : IBackend
    {
        /// <summary>
        /// Sends an image processing request to a VisionGrabber relay server.
        /// </summary>
        /// <param name="base64Image">The image encoded as a base64 string.</param>
        /// <param name="userPrompt">The prompt to send with the image.</param>
        /// <returns>The text generated by the remote relay server.</returns>
        public async Task<string> SendImageRequest(string base64Image, string userPrompt)
        {
            var settings = SettingsManager.Current;
            string address = settings.RelayClientAddress;

            if (string.IsNullOrWhiteSpace(address))
                return "Error: Relay Server Address is missing. Please check Settings.";

            address = address.TrimEnd('/');

            using (var client = new HttpClient())
            {
                client.Timeout = TimeSpan.FromMinutes(5); // Increased timeout for processing
                client.DefaultRequestHeaders.ExpectContinue = false;

                var payload = new
                {
                    image = base64Image,
                    prompt = userPrompt
                };

                var json = JsonConvert.SerializeObject(payload);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                try 
                {
                    var response = await client.PostAsync($"{address}/process", content);
                    var responseString = await response.Content.ReadAsStringAsync();
                    
                    if (!response.IsSuccessStatusCode)
                    {
                        return $"Error: Relay Server returned {response.StatusCode} - {responseString}";
                    }

                    return responseString;
                }
                catch (TaskCanceledException)
                {
                    return "Error: Relay Server timed out after 5 minutes.";
                }
                catch (Exception ex)
                {
                    return $"Error connecting to Relay Server at {address}:\n" + ex.Message;
                }
            }
        }
    }
}
