using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using VisionGrabber.Utilities;

namespace VisionGrabber.Backends
{
    /// <summary>
    /// Implements a backend that communicates with a remote llama-server instance on the network.
    /// </summary>
    public class RemoteLlamaBackend : IBackend
    {
        /// <summary>
        /// Sends an image processing request to a remote llama-server.
        /// </summary>
        /// <param name="base64Image">The image encoded as a base64 string.</param>
        /// <param name="userPrompt">The prompt to send with the image.</param>
        /// <returns>The text generated by the model.</returns>
        public async Task<string> SendImageRequest(string base64Image, string userPrompt)
        {
            var settings = SettingsManager.Current;
            string address = settings.RemoteLlamaAddress;

            if (string.IsNullOrWhiteSpace(address))
                return "Error: Remote Llama Address is missing. Please check Settings.";

            // Normalize the address by removing trailing slashes
            address = address.TrimEnd('/');

            using (var client = new HttpClient())
            {
                var payload = new
                {
                    messages = new[]
                    {
                        new {
                            role = "user",
                            content = new object[]
                            {
                                new { type = "text", text = userPrompt },
                                new { type = "image_url", image_url = new { url = $"data:image/png;base64,{base64Image}" } }
                            }
                        }
                    },
                    temperature = 0.1, 
                    max_tokens = 500
                };

                var json = JsonConvert.SerializeObject(payload);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                try 
                {
                    var response = await client.PostAsync($"{address}/v1/chat/completions", content);
                    var responseString = await response.Content.ReadAsStringAsync();
                    
                    if (!response.IsSuccessStatusCode)
                    {
                        return $"Error: Server returned {response.StatusCode} - {responseString}";
                    }

                    dynamic result = JsonConvert.DeserializeObject(responseString);
                    
                    string text = result?.choices?[0]?.message?.content; 
                    return text ?? "No text found.";
                }
                catch (Exception ex)
                {
                    return "Error connecting to Remote Llama: " + ex.Message;
                }
            }
        }
    }
}
